
const array = [{
    name: 'cookie',
    description: '🍪 **Cookie**\na tasty snack.',
    canUse: true,
    canBuy: true,
    displayOnShop: true,
    sellAmount: 10,
    price: 50,
    keep: false,
    run: async (bot, message, args) => {
        const cookieRandom = [
            'You ate a cookie as you was feeling hungry.',
            'You choked on a cookie and almost died.',
            'The cookie tasted great.'
        ];
        const yes = cookieRandom[Math.floor(Math.random() * cookieRandom.length)];
        message.channel.send(`${yes}`);
    }
},
{
    name: 'padlock',
    description: ` **Padlock**\nsecure your wallet from those sneaky robbers`,
    canUse: false,
    canBuy: true,
    displayOnShop: true,
    sellAmount: 2000,
    price: 10000,
    keep: true,
},
{
    name: 'fishingrod',
    description: '🎣 **Fishing Rod** \nuse this to catchs fish',
    canUse: false,
    canBuy: true,
    displayOnShop: true,
    sellAmount: 3000,
    price: 15000,
    keep: true,
},
{
    name: 'common',
    description: '🐟 **Common Fish** \nsell common to make money.',
    canUse: false,
    canBuy: false,
    displayOnShop: false,
    sellAmount: 25,
    price: 0,
    keep: true,
},
{
    name: 'uncommon',
    description: '🐠 **Uncommon Fish** \nsell uncommon to make money.',
    canUse: false,
    canBuy: false,
    displayOnShop: false,
    sellAmount: 50,
    price: 0,
    keep: true,
},
{
    name: 'rare',
    description: '🦑 **Rare Fish** \nsell rare to make money.',
    canUse: false,
    canBuy: false,
    displayOnShop: false,
    sellAmount: 125,
    price: 0,
    keep: true,
},
{
    name: 'veryrare',
    description: '🐡 **Very Rare Fish** \nsell veryrare to make money.',
    canUse: false,
    canBuy: false,
    displayOnShop: false,
    sellAmount: 75,
    price: 0,
    keep: true,
},
{
    name: 'legendary',
    description: `**Legendary Fish** \nsell legendary to make money.`,
    canUse: false,
    canBuy: false,
    displayOnShop: false,
    sellAmount: 200,
    price: 0,
    keep: true,
},
{
    name: 'junk',
    description: ` **Junk** \nsell junk to make money.`,
    canUse: false,
    canBuy: false,
    displayOnShop: false,
    sellAmount: 10,
    price: 0,
    keep: true,
},
{
    name: 'banknote',
    description: `📜 **Bank Note** \nmore bank space.`,
    canUse: true,
    canBuy: true,
    displayOnShop: true,
    sellAmount: 6667,
    price: 20000,
    keep: false,
    run: async (bot, message, args) => {
        const random = Math.ceil((Math.random() * 10000) + 10000);
        const e = await bot.giveBankSpace(message.author.id, random);
        message.channel.send(`You redeemed a banknote, which increases your bank space by **${random.toLocaleString()}**. You now have **${e.bankSpace.toLocaleString()}** bank space.`);
    }
},
{
    name: 'rifle',
    description: ` **Rifle**\nuse this to kills animals`,
    canUse: false,
    canBuy: true,
    displayOnShop: true,
    sellAmount: 3000,
    price: 22500,
    keep: true,
},
{
    name: 'deer',
    description: '🦌 **Deer**\nsell deer to make money.',
    canUse: false,
    canBuy: false,
    displayOnShop: false,
    sellAmount: 50,
    price: 0,
    keep: true,
},
{
    name: 'bear',
    description: '🐻 **Bear**\nsell bear to make money.',
    canUse: false,
    canBuy: false,
    displayOnShop: false,
    sellAmount: 60,
    price: 0,
    keep: true,
},
{
    name: 'duck',
    description: '🦆 **Duck**\nsell duck to make money.',
    canUse: false,
    canBuy: false,
    displayOnShop: false,
    sellAmount: 25,
    price: 0,
    keep: true,
},
{
    name: 'pig',
    description: '🐷 **Pig**\nsell pig to make money.',
    canUse: false,
    canBuy: false,
    displayOnShop: false,
    sellAmount: 80,
    price: 0,
    keep: true,
},
{
    name: 'cow',
    description: '🐮 **Cow**\nsell cow to make money.',
    canUse: false,
    canBuy: false,
    displayOnShop: false,
    sellAmount: 120,
    price: 0,
    keep: true,
},
{
    name: 'fox',
    description: '🦊 **Fox**\nsell fox to make money.',
    canUse: false,
    canBuy: false,
    displayOnShop: false,
    sellAmount: 100,
    price: 0,
    keep: true,
},
{
    name: 'rabbit',
    description: '🐰 **Rabbit**\nsell rabbit to make money.',
    canUse: false,
    canBuy: false,
    displayOnShop: false,
    sellAmount: 30,
    price: 0,
    keep: true,
},
{
    name: 'chicken',
    description: '🐔 **Chicken**\nsell chicken to make money.',
    canUse: false,
    canBuy: false,
    displayOnShop: false,
    sellAmount: 50,
    price: 0,
    keep: true,
},
{
    name: 'boar',
    description: '🐗 **Boar**\nsell boar to make money.',
    canUse: false,
    canBuy: false,
    displayOnShop: false,
    sellAmount: 10,
    price: 0,
    keep: true,
},
{
    name: 'pickaxe',
    description: ` **Pickaxe**\nuse this to mine gems`,
    canUse: false,
    canBuy: true,
    displayOnShop: true,
    sellAmount: 3000,
    price: 30000,
    keep: true,
},
{
    name: 'gem',
    description: '💎 **Gem**\nsell gems to make money.',
    canUse: false,
    canBuy: false,
    displayOnShop: false,
    sellAmount: 10,
    price: 0,
    keep: true,
},
{
    name: 'diamond',
    description: ` **Diamond Gem** \nsell the diamond to make money.`,
    canUse: false,
    canBuy: false,
    displayOnShop: false,
    sellAmount: 200,
    price: 0,
    keep: true,
},
{
    name: 'ruby',
    description: ` **Ruby Gem** \nsell the ruby to make money.`,
    canUse: false,
    canBuy: false,
    displayOnShop: false,
    sellAmount: 225,
    price: 0,
    keep: true,
},
{
    name: 'gade',
    description: ` **Gade Gem** \nsell the gade to make money.`,
    canUse: false,
    canBuy: false,
    displayOnShop: false,
    sellAmount: 300,
    price: 0,
    keep: true,
},
{
    name: 'amethyst',
    description: ` **Amethyst Gem** \nsell the amethyst to make money.`,
    canUse: false,
    canBuy: false,
    displayOnShop: false,
    sellAmount: 350,
    price: 0,
    keep: true,
},
{
    name: 'precious',
    description: ` **Precious Gem** \nsell the precious to make money.`,
    canUse: false,
    canBuy: false,
    displayOnShop: false,
    sellAmount: 500,
    price: 0,
    keep: true,
},
{
    name: 'axe',
    description: `**Axe**\nuse this to chops trees down`,
    canUse: true,
    canBuy: true,
    displayOnShop: true,
    sellAmount: 3000,
    price: 20000,
    keep: true,
    run: async (bot, message, args) => {
        const treeAmount = Math.round(Math.random() * 1) + 1;
        const data = await bot.fetchUser(message.author.id);
        message.channel.send(`You went into the woods and chopped down **${treeAmount}** x Tree 🌲`);
        const findItem = data.items.find(i => i.name.toLowerCase() == 'tree');
        let userInv = data.items.filter(i => i.name.toLowerCase() !== 'tree');
        if (findItem) {
            userInv.push({ name: 'tree', amount: (findItem.amount + treeAmount), description: '🌲 **Tree**\nsell trees to make money.' });
            data.items = userInv;
            await data.save();
        } else {
            userInv.push({ name: 'tree', amount: treeAmount, description: '🌲 **Tree**\nsell trees to make money.' });
            data.items = userInv;
            await data.save();
        }
    }
},
{
    name: 'tree',
    description: '🌲 **Tree**\nsell trees to make money.',
    canUse: false,
    canBuy: false,
    displayOnShop: false,
    sellAmount: 500,
    price: 0,
    keep: true,
},
{
    name: 'luckyclover',
    description: `**Lucky Clover**\nincrease your chances of successful robbery`,
    canUse: false,
    canBuy: true,
    displayOnShop: true,
    sellAmount: 4000,
    price: 10000,
    keep: false,
},
{
    name: 'rainbowcoin',
    description: ` **Rainbow Coin**`,
    canUse: false,
    canBuy: true,
    displayOnShop: true,
    sellAmount: 50000000,
    price: 100000000,
    keep: false,
},
{
    name: 'goldcoin',
    description: ` **Gold Coin**`,
    canUse: false,
    canBuy: true,
    displayOnShop: true,
    sellAmount: 25000000,
    price: 50000000,
    keep: false,
},
{
    name: 'silvercoin',
    description: `**Silver Coin**`,
    canUse: false,
    canBuy: true,
    displayOnShop: true,
    sellAmount: 7500000,
    price: 15000000,
    keep: false,
},
{
    name: 'bronzecoin',
    description: ` **Bronze Coin**`,
    canUse: false,
    canBuy: true,
    displayOnShop: true,
    sellAmount: 2500000,
    price: 5000000,
    keep: false,
},
{
    name: 'trophy',
    description: `**Trophy**`,
    canUse: false,
    canBuy: true,
    displayOnShop: true,
    sellAmount: 50000000,
    price: 100000000,
    keep: false,
}
];

module.exports = array;
